DROP TABLE IF EXISTS EXPERT;
CREATE TABLE EXPERT (
expert_id INT AUTO_INCREMENT  PRIMARY KEY,
expert_name VARCHAR(50),
expert_status VARCHAR(30) NOT NULL,
available_hours_for_day INT NOT NULL
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER (
customer_id INT AUTO_INCREMENT  PRIMARY KEY,
customer_name VARCHAR(50)
);

DROP TABLE IF EXISTS ACCOUNTING_TASK;
CREATE TABLE ACCOUNTING_TASK (
accounting_task_id VARCHAR(20) PRIMARY KEY,
accounting_task_name VARCHAR(50),
deadline INT NOT NULL,
time_needed INT NOT NULL,
dependent_task_id VARCHAR(20)
);

DROP TABLE IF EXISTS CUSTOMER_REQUEST;
CREATE TABLE CUSTOMER_REQUEST (
customer_request_id INT AUTO_INCREMENT  PRIMARY KEY,
customer_id INT NOT NULL,
request_id VARCHAR(40) NOT NULL,
request_status VARCHAR(30)
);


